create table member(
    sid bigint generated by default as identity,
    id varchar(255),
    password varchar(255),
    primary key(sid, id)
);

create table post(
    pid bigint generated by default as identity,
    id varchar(255),
    title varchar(50),
    content varchar(255),
    primary key(pid)
);